[2023-10-20 23:23:25,423] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: mi_primer_dag_v3.primera_tarea scheduled__2023-08-20T00:00:00+00:00 [queued]>
[2023-10-20 23:23:25,442] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: mi_primer_dag_v3.primera_tarea scheduled__2023-08-20T00:00:00+00:00 [queued]>
[2023-10-20 23:23:25,443] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-10-20 23:23:25,444] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2023-10-20 23:23:25,444] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-10-20 23:23:25,485] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): primera_tarea> on 2023-08-20 00:00:00+00:00
[2023-10-20 23:23:25,491] {standard_task_runner.py:52} INFO - Started process 3732 to run task
[2023-10-20 23:23:25,495] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'mi_primer_dag_v3', 'primera_tarea', 'scheduled__2023-08-20T00:00:00+00:00', '--job-id', '1146', '--raw', '--subdir', 'DAGS_FOLDER/primer_dag_v3.py', '--cfg-path', '/tmp/tmpmja_wv4a', '--error-file', '/tmp/tmpad1ac7xd']
[2023-10-20 23:23:25,497] {standard_task_runner.py:80} INFO - Job 1146: Subtask primera_tarea
[2023-10-20 23:23:25,634] {task_command.py:371} INFO - Running <TaskInstance: mi_primer_dag_v3.primera_tarea scheduled__2023-08-20T00:00:00+00:00 [running]> on host dfdda228c9fc
[2023-10-20 23:23:25,773] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=DavidBU
AIRFLOW_CTX_DAG_ID=mi_primer_dag_v3
AIRFLOW_CTX_TASK_ID=primera_tarea
AIRFLOW_CTX_EXECUTION_DATE=2023-08-20T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-08-20T00:00:00+00:00
[2023-10-20 23:23:25,775] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-10-20 23:23:25,776] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo hola mundo, esta es nuestra primera tarea!']
[2023-10-20 23:23:25,791] {subprocess.py:85} INFO - Output:
[2023-10-20 23:23:25,795] {subprocess.py:92} INFO - hola mundo, esta es nuestra primera tarea!
[2023-10-20 23:23:25,811] {subprocess.py:96} INFO - Command exited with return code 0
[2023-10-20 23:23:25,816] {local_task_job.py:84} ERROR - Received SIGTERM. Terminating subprocesses
[2023-10-20 23:23:25,828] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 3732. PIDs of all processes in the group: [3732]
[2023-10-20 23:23:25,831] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 3732
[2023-10-20 23:23:25,839] {taskinstance.py:1561} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-10-20 23:23:25,842] {subprocess.py:103} INFO - Sending SIGTERM signal to process group
[2023-10-20 23:23:25,844] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2412, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 188, in set
    dag_run_id = session.query(DagRun.id).filter_by(dag_id=dag_id, run_id=run_id).scalar()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2879, in scalar
    ret = self.one()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2856, in one
    return self._iter().one()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2897, in _iter
    execution_options={"_sa_orm_load_options": self.load_options},
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1688, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1530, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3197, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3276, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3243, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 584, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1562, in signal_handler
    self.task.on_kill()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 200, in on_kill
    self.subprocess_hook.send_sigterm()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/subprocess.py", line 105, in send_sigterm
    os.killpg(os.getpgid(self.sub_process.pid), signal.SIGTERM)
ProcessLookupError: [Errno 3] No such process
[2023-10-20 23:23:25,882] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=mi_primer_dag_v3, task_id=primera_tarea, execution_date=20230820T000000, start_date=20231020T232325, end_date=20231020T232325
[2023-10-20 23:23:25,911] {standard_task_runner.py:97} ERROR - Failed to execute job 1146 for task primera_tarea ([Errno 3] No such process; 3732)
[2023-10-20 23:23:25,940] {process_utils.py:75} INFO - Process psutil.Process(pid=3732, status='terminated', exitcode=1, started='23:23:25') (3732) terminated with exit code 1
[2023-10-20 23:23:25,941] {local_task_job.py:156} INFO - Task exited with return code 143
[2023-10-20 23:23:26,022] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
